### ISSUE TITLE
Can I access basic variables pathinfo??

### ISSUE THREAD

**Issue by ffd8** [hamoid/video_export_processing#18]
Amaaazing lib! I've never had such ease getting video out of Processing!

I'm building a small animation tool (application for end student.. not run from Processing) that allows video export and need to find an elegant way to make sure they have linked FFMPEG, therefore I was trying to access either the boolean you have for 'ffmpegFound' or a string of the path if there is one. This way I can use my own controlp5 to have them find FFMPEG, then each time they run the app, confirm it's still there and hasn't been moved around. Maybe I'm just dumb and don't know how to reach these variables inside the lib? I tried and it told me that it 'is not visible'... Do they need explicit one line functions in the script to return those variables?

As a tip and 'bug' I ran into while beta-testing.. if one has linked FFMPEG, then moves it– it would be great for VideoExport to simply ask again for the new path and set that in the preferences. Maybe by always doing a quick 'fileExists' check with the path in settings before actually exporting? One last detail, there's no info/question/text when the popup appears the first time one needs to set the path.. just a window. In my case it's especially strange because I first present a file dialog for where to save the exported video to.

**Comment by hamoid** [comment]
I'm happy you find it useful :) Thanks for your suggestions! I'll use them to improve the library.

The variable you are trying to access is protected, therefore it can't be accessed from outside. I'll think about how to make it accessible and let you know.
