### ISSUE TITLE
ArrayIndexOutOfBoundException when using pixelDensity(2)

### ISSUE THREAD

**Issue by federico-pepe** [hamoid/video_export_processing#19]
Using pixelDensity(2) in the sketch with this library triggers an error.

**Comment by hamoid** [comment]
Thanks for reporting this. Unfortunately I don't have a high-dpi device to test on at the moment. Do you know enough about Processing and retina displays to help me fix this?

**Comment by hamoid** [comment]
Does it happen with the included example programs, just by adding pixelDensity(2)? Is your display retina / high-density?

**Comment by federico-pepe** [comment]
I have  a MPB 15" with Retina Display. The included examples work fine because the error happens only if I add pixelDensity(2) to the sketch. I've been using Processing for a while so I might help even if I never developed libraries or something like that.

**Comment by hamoid** [comment]
Which Processing version? Have you successfully run a simple sketch with pixelDensity(2) which uses loadPixels(), pixels[...] and updatePixels() (without the video export library)?

**Comment by federico-pepe** [comment]
I'm using Processing 3.1.1, this sketch (taken from your examples) runs flawlessly
```
void setup() {
  size(600, 600);
  noStroke();
  pixelDensity(2);
}
void draw() {
  loadPixels();
  for(int i=0; i<pixels.length; i++) {
    pixels[i] = (int)random(-99999, -33333);
  }
  updatePixels();
}

**Comment by hamoid** [comment]
The latest version was updated to take into account high dpi screens. If this does not solve the issue please re-open this.
