### ISSUE TITLE
ffmpeg failed

### ISSUE THREAD

**Issue by rtavakko** [hamoid/video_export_processing#2]
Running the example sketches without locating the ffmpeg executable causes the sketch not to run anymore giving the error message:

VideoExport error: Ffmpeg failed. Study basic.mp4.txt for more details.
Could not run the sketch (Target VM failed to initialize).

Processing version used: 3.0a5

**Comment by hamoid** [comment]
Which OS? Did it produce a basic.mp4.txt file to find out what went wrong?

**Comment by rtavakko** [comment]
Windows 7 64-bit. Yes it made an empty basic.mp4.txt file.

**Comment by hamoid** [comment]
Ok, I have to find someone with Win7 to test. Meanwhile, what if you locate the ffmpeg executable? Does it work then?

**Comment by rtavakko** [comment]
It does not prompt for that anymore. I tried deleting and replacing the folder a few times to no avail.

**Comment by hamoid** [comment]
Maybe videoExport.forgetFfmpegPath() helps :)

**Comment by rtavakko** [comment]
Yes it did! Thank you so much, really appreciate your help!

**Comment by hamoid** [comment]
^_^
