### ISSUE TITLE
Add option to pass arbitrary ffmpeg command line

### ISSUE THREAD

**Issue by iongion** [hamoid/video_export_processing#23]
To avoid additional feature requests and to allow complete control of ffmpeg:
- output format
- custom filters
- custom codec
- custom codec parameters

**Comment by hamoid** [comment]
Good idea :+1: I'll think how to best implement that.

**Comment by hamoid** [comment]
This is now possible. When you run the library the first time it produces a settings.json file located in the library folder. This file contains the two ffmpeg commands that are executed by the library. If you are careful you can tweak them :) You could for instance 

* add a filter to make the result grayscale, apply curves, darken, brighten, tint, blur... see https://ffmpeg.org/ffmpeg-filters.html#Video-Filters
* superimpose your name and URL to your movies

If anyone produces an interesting effect, feel free to share it below :)
