### ISSUE TITLE
Not clear how to update ffmpeg position

### ISSUE THREAD

**Issue by mikima** [hamoid/video_export_processing#24]
Moved ffmpeg to another folder, clicked by error on another file when asked to select ffmpeg position.
Deleted the file, problem persists.

Processing keeps crashing with this error:

`java.io.IOException: Cannot run program "[removed]/07.pdf": error=2, No such file or directory`

**Comment by hamoid** [comment]
Hi @mikima 

There's two closed issues mentioning the solution: try running videoExport.forgetFfmpegPath(); once.
Sorry for not explaining this clearly.

I'll leave this issue open to remind myself to document this better. I could even call that function automatically if the program fails to execute.

**Comment by mikima** [comment]
Thanks @hamoid, it worked!

**Comment by hamoid** [comment]
It's included on the FAQ now, and the home page shows FAQ as bold. I hope it's more noticeable.
