### ISSUE TITLE
videoExport.forgetFfmpegPath();  does not function

### ISSUE THREAD

**Issue by Lorits** [hamoid/video_export_processing#26]
I have indicated a wrong path for ffmpeg, and running videoExport.forgetFfmpegPath(); once does not allow me to choose another path.

**Comment by hamoid** [comment]
Hi! Which OS? Can you try on the most recent version of the library? Which version of Processing?

**Comment by hamoid** [comment]
In the next version there is a settings.json file found in the videoExport library folder. This json file can be modified and deleted if necessary. You can try the version here:
https://www.funprogramming.org/VideoExport-for-Processing/download/VideoExport-17.zip
