### ISSUE TITLE
something like finishMove()

### ISSUE THREAD

**Issue by clankill3r** [hamoid/video_export_processing#28]
There is no other way to finish a movie other then dispose().
Since this set's all things to null the user has to create a new VideoExport instance.

It would be nice if you can start and finish making movies.

**Comment by hamoid** [comment]
You are right. I'll add such a method.

**Comment by hamoid** [comment]
I'll push a new version very soon. I'm testing and it seems to work fine: now it's possible to export multiple movies while running one sketch.

What platform are you on, @clankill3r ? Could you help me test in OSX or Windows? I'm on Linux...

**Comment by clankill3r** [comment]
I'm on both windows and OSX

**Comment by hamoid** [comment]
The latest version includes startMovie and endMovie(), and an example for producing many movies from one sketch.
