### ISSUE TITLE
Video output fullscreen (1920x1080) creates corrupted file

### ISSUE THREAD

**Issue by fgonzalez-cespi** [hamoid/video_export_processing#32]
I tried to capture a video while having the screen size set to fullscreen, with my display set at 1920x1080.
It seems to be running well but when I end the video recording, the file doesn't play.

I have successfully recorded a video in 640 x 480 resolution, before.

I'm running processing 3.2.3 on Windows 7 Enterprise with a static ffmpeg file dowloaded.

This is the content of the ffmpeg log, for a try  with about 5 seconds of output:
ffmpeg version N-82966-g6993bb4 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 5.4.0 (GCC)
  configuration: --enable-gpl --enable-version3 --enable-dxva2 --enable-libmfx --enable-nvenc --enable-avisynth --enable-bzlib --enable-fontconfig --enable-frei0r --enable-gnutls --enable-iconv --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libfreetype --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenh264 --enable-libopenjpeg --enable-libopus --enable-librtmp --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzimg --enable-lzma --enable-decklink --enable-zlib
  libavutil      55. 43.100 / 55. 43.100
  libavcodec     57. 70.100 / 57. 70.100
  libavformat    57. 61.100 / 57. 61.100
  libavdevice    57.  2.100 / 57.  2.100
  libavfilter     6. 68.100 /  6. 68.100
  libswscale      4.  3.101 /  4.  3.101
  libswresample   2.  4.100 /  2.  4.100
  libpostproc    54.  2.100 / 54.  2.100
Input #0, rawvideo, from 'pipe:':
  Duration: N/A, start: 0.000000, bitrate: 1492992 kb/s
    Stream #0:0: Video: rawvideo (RGB[24] / 0x18424752), rgb24, 1920x1080, 1492992 kb/s, 30 tbr, 30 tbn, 30 tbc
[libx264 @ 000000000048e460] using cpu capabilities: MMX2 SSE2Fast LZCNT
[libx264 @ 000000000048e460] profile High, level 4.0
[libx264 @ 000000000048e460] 264 - core 148 r2744 b97ae06 - H.264/MPEG-4 AVC codec - Copyleft 2003-2016 - http://www.videolan.org/x264.html - options: cabac=1 ref=3 deblock=1:0:0 analyse=0x3:0x113 me=hex subme=7 psy=1 psy_rd=1.00:0.00 mixed_ref=1 me_range=16 chroma_me=1 trellis=1 8x8dct=1 cqm=0 deadzone=21,11 fast_pskip=1 chroma_qp_offset=-2 threads=6 lookahead_threads=1 sliced_threads=0 nr=0 decimate=1 interlaced=0 bluray_compat=0 constrained_intra=0 bframes=3 b_pyramid=2 b_adapt=1 b_bias=0 direct=1 weightb=1 open_gop=0 weightp=2 keyint=250 keyint_min=25 scenecut=40 intra_refresh=0 rc_lookahead=40 rc=crf mbtree=1 crf=15.0 qcomp=0.60 qpmin=0 qpmax=69 qpstep=4 ip_ratio=1.40 aq=1:1.00
Output #0, mp4, to 'C:\Users\medicenfranito\Documents\Processing\caquitas\sketch_161230a\options.mp4':
  Metadata:
    comment         : Exported using VideoExport for Processing - https://github.com/hamoid/VideoExport-for-Processing
    encoder         : Lavf57.61.100
    Stream #0:0: Video: h264 (libx264) ([33][0][0][0] / 0x0021), yuv420p, 1920x1080, q=-1--1, 30 fps, 15360 tbn, 30 tbc
    Metadata:
      encoder         : Lavc57.70.100 libx264
    Side data:
      cpb: bitrate max/min/avg: 0/0/0 buffer size: 0 vbv_delay: -1
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> h264 (libx264))
frame=   13 fps=0.0 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
frame=   27 fps= 26 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
frame=   43 fps= 27 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
frame=   50 fps= 24 q=0.0 size=       0kB time=00:00:00.00 bitrate=N/A speed=   0x    
frame=   58 fps= 22 q=21.0 size=     901kB time=00:00:00.16 bitrate=44249.8kbits/s speed=0.0639x    
frame=   67 fps= 21 q=21.0 size=    1060kB time=00:00:00.46 bitrate=18607.2kbits/s speed=0.149x    
frame=   77 fps= 21 q=21.0 size=    1214kB time=00:00:00.80 bitrate=12427.2kbits/s speed=0.219x    
frame=   88 fps= 21 q=21.0 size=    1374kB time=00:00:01.16 bitrate=9650.5kbits/s speed=0.278x    
frame=   97 fps= 21 q=21.0 size=    1509kB time=00:00:01.46 bitrate=8430.6kbits/s speed=0.311x    
frame=  106 fps= 20 q=21.0 size=    1657kB time=00:00:01.76 bitrate=7684.9kbits/s speed=0.337x    
frame=  116 fps= 20 q=21.0 size=    1806kB time=00:00:02.10 bitrate=7043.5kbits/s speed=0.361x    
frame=  126 fps= 20 q=21.0 size=    1954kB time=00:00:02.43 bitrate=6579.4kbits/s speed=0.385x

**Comment by fgonzalez-cespi** [comment]
UPDATE:

If I set videoExport.dontSaveDebugInfo(), the display freezes in 00:00:04, and the sketchs display stops working (even if the audio keeps playing).

I had to start the TaskManager (Ctrl+Alt+Supr) to get back control of the desktop, and when I stopped the sketch, the video was created, uncorrupted, but just as long as the display was working (four seconds).

**Comment by hamoid** [comment]
Hi, could you please give this update a try: https://www.funprogramming.org/VideoExport-for-Processing/download/VideoExport-17.zip It does work for me on Linux, but I added some Windows specific changes I can't test myself.

**Comment by hamoid** [comment]
I'll close this, as the library now uses a different approach to avoid saving debug info. Please open a new issue if there's a problem with not saving debug information on the latest version of the library.
