### ISSUE TITLE
using video_export with python

### ISSUE THREAD

**Issue by pietrondo** [hamoid/video_export_processing#34]
Hi, I'm using processing with python mode.
How Can I use the video_export library with python?
"this" doesn't exist in python.. So? how Can I do?

thx

**Comment by hamoid** [comment]
Hi, according to the peasycam example in this wiki https://github.com/jdf/processing.py/wiki you can use "this"... Anyway I haven't tried, so I don't know if it will work or not. Let me know! :)

**Comment by hamoid** [comment]
I just made an example work:

```python
add_library('VideoExport')

def setup():
    global videoExport
    size(600, 600)
    videoExport = VideoExport(this, "hello.mp4")    
    videoExport.startMovie()

def draw():
    global videoExport
    background(22, 44, 88)
    rect(frameCount * frameCount % width, 0, 40, height)
    if(frameCount > 5):
        videoExport.saveFrame()

def keyPressed():
    if (key == 'q'):
        videoExport.endMovie()
        exit()

```
