### ISSUE TITLE
don't ask for ffmpeg path

### ISSUE THREAD

**Issue by mms92** [hamoid/video_export_processing#40]
i'm currently using the webcam saving exemple , and when i run it , it didn't ask me for the path of ffmpeg , still , i didn't get any error
in other hand , when i run the option example , i do have the pop-up for choose that path

**Comment by hamoid** [comment]
Hi! When you encounter an issue and later resolve, it's useful to let other people know how you did it, so we can all learn from each other :) Good that you figured it out in any case!

**Comment by mms92** [comment]
it's just me being an idiot, there where no issue with your libraries at all , i just forgot to add the video.startMovie() in the setup() x)
