### ISSUE TITLE
setAudioFileName() + setDebugging(false) crashes with NullPointerException on endMovie()

### ISSUE THREAD

**Issue by ffd8** [hamoid/video_export_processing#41]
First off, thaaankyou the new AudioViz workaround is amazing! Gives me perfectly synced 25fps w/ audio outputs. I do a 2–pass export (first I export a wav track, then the visuals after text analyses on it).

However, I ran into a craazy bug that threw me off for a few hours when I thought all was perfect.. for some reason, turning on `setDebugging(false)` kills videoExport's own `endMovie()` function with a NullPointerException – when combined with this AudioViz `setAudioFileName()` function. 

Just managed to recreate it within your example 'withAudioViz', by adding that line `videoExport.setDebugging(false);`. The order didn't seem to matter and only stopped crashing once disabling `setAudioFileName()`

**Comment by hamoid** [comment]
Thank you, I'll look into it.
