### ISSUE TITLE
setFfmpegPath() method

### ISSUE THREAD

**Issue by liquid600pgm** [hamoid/video_export_processing#45]
Hi. I am developing a program and would like to include ffmpeg with it, so that the user doesn't have to choose the ffmpeg path manually. I have already posted this suggestion on the forum thread, but it seems like it never got implemented.

**Comment by hamoid** [comment]
I'll get it done. Thanks for the idea :)

**Comment by hamoid** [comment]
Done! :) Updating the website now...
