### ISSUE TITLE
Video Output not match with FrameRate 

### ISSUE THREAD

**Issue by KeremTurkyilmaz** [hamoid/video_export_processing#52]
Hi, 

I'm trying to create a program that export an audio Waveform derived by an audio file. But when I have the render the video is not match with the original frameRate of my Sketch. 

I run the sketch at 60 FrameRate but I think the output video is at 30 FPS.

There's a way to duplicate the frameRate of the output, or I'm missing something different ?

**Comment by hamoid** [comment]
I guess you figured it out? :)

**Comment by KeremTurkyilmaz** [comment]
Hi,

Yes, but I have another problem, I want to export the video and audio together but I don’t know how integrate that in my sketch.

Thank you !

Kerem Türkyilmaz
kerem.turkyilmaz@outlook.it<mailto:kerem.turkyilmaz@outlook.it>
www.kerem.ch<http://www.kerem.ch>










Il giorno 17 lug 2018, alle ore 09:40, Abe Pazos <notifications@github.com<mailto:notifications@github.com>> ha scritto:


I guess you figured it out? :)

**Comment by hamoid** [comment]
Please ask in the Processing forum as that's a general Processing question
