### ISSUE TITLE
Exported video very low framerate

### ISSUE THREAD

**Issue by leolibertino** [hamoid/video_export_processing#55]
Hi, great library, but I have an issue, maybe you could tell me what I am doing wrong?

I'm exporting the video like this:

```
import com.hamoid.*;
VideoExport video;

void setup () {
  ...
  video = new VideoExport(this, "test.mp4");
  video.startMovie();
}

void draw () {
  ...
  video.saveFrame();
}

void keyPressed () {
  if (key == 'q') {
    video.endMovie();
    exit();
  }
}

```

The video is exported, but it runs at a very very low framerate, while the sketch while I was recording was going well. I have also tried to set explicitly frameRate(60) in the setup method but nothing changes.

Am I doing something wrong?

Thank you!

**Comment by hamoid** [comment]
Hi. There are two frame rates: the one of your program, and the one of your video. The default frame rate for videos is 30. If your program runs at 60 fps, that means the resulting video will play back at half the speed. 30 fps is the default for internet video. Video platforms now support 60 fps in some cases.

If you call `frameRate(30);` or `video.setFrameRate(60);` does the look of the sketch equal that of the produced video?

**Comment by leolibertino** [comment]
Thank you very much for your answer, that resolved my issue!
