### ISSUE TITLE
The export fails when closing the display instead of clicking stop

### ISSUE THREAD

**Issue by charlessowers** [hamoid/video_export_processing#6]
Hi I notice that VideoExport only works at size(600, 600). Is that true? Can it be made to export at different sizes?

**Comment by charlessowers** [comment]
Ooh, I take it back. It is not the size() function causing the problem. The exports fails if you close the display window rather than "stop" the sketch from the IDE....

**Comment by hamoid** [comment]
I noticed that too. Do you know why that might happen?

**Comment by Jacowaco** [comment]
I experience the same issue on Windows, closing with ESC or the close button generates a corrupted file. Stopping from the IDE generates a good video.

**Comment by hamoid** [comment]
It seems to be a Processing issue: https://github.com/processing/processing/issues/4445

**Comment by hamoid** [comment]
@Jacowaco @charlessowers You could try adding something like this to your program:

```
void keyPressed() {
  if(key == 'q') {
    videoExport.dispose();
    exit();
  }
}
```

Then you have to remember to quit your program pressing 'q'. I know it's inconvenient, but until this bug is fixed in Processing, we need a way to manually make sure all the data is saved to the video file before closing it.

**Comment by Jacowaco** [comment]
Great! Thanks for the answer :)

**Comment by oysterboy** [comment]
Hello hamoid!
Thanks for the great library! - 
one more question to the dispose() topic.
Should manual calling videoExport.dispose(); 
be enough to make the resulting file playable?
Or do I definitely need to exit Processing(by whichever method)?

My goal is to export separate video files,
which will then be played back by the same Processing app. 

--------------------------------------------------------------------------------------
My setup is Win 8.1 & Pprocessing 3.1.1,
and i get playable .mp4s after i close the sketch -
for three ways of exiting ( ESC, X on Window, Stop button in IDE)

**Comment by hamoid** [comment]
Hi @oysterboy! Interesting use case! I haven't tried that. It would be great if you can try and report back :) When I get a minute I may try to make a recursive video filter: play back a video from Processing, doing something to each frame, while exporting a new file. Then repeat the process using the produced video file as input. And repeat :)

**Comment by oysterboy** [comment]
Did some more testing with the basics,
I will use shorthand X (for the close button of the applet window, ESC for the Escape key and STOP for rthe stop button in the Processing IDE.... 
Still on Win 8.1, Processing 3.1.1.
-
The basic.pde example, normal renderer: 
STOP works, ESC doesn't, X doesn't 
The basic.pde example, P2D renderer
STOP works, ESC doesn't, X works
-
Manually calling videoExport.dispose(); 
without calling exit() throws:
java.io.IOException: Stream Closed
	at java.io.FileOutputStream.writeBytes(Native Method)
	at java.io.FileOutputStream.write(FileOutputStream.java:326)
	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
	at java.io.FilterOutputStream.write(FilterOutputStream.java:97)
	at com.hamoid.VideoExport.saveFrame(Unknown Source)
	at sketch_160531b_ffmpeg_basic.draw(sketch_160531b_ffmpeg_basic.java:32)
	at processing.core.PApplet.handleDraw(PApplet.java:2403)
	at processing.awt.PSurfaceAWT$12.callDraw(PSurfaceAWT.java:1527)
	at processing.core.PSurfaceNone$AnimationThread.run(PSurfaceNone.java:316)
VideoExport error: Ffmpeg failed. 

ffmpeg debug file attached.
[basic.mp4.txt](https://github.com/hamoid/video_export_processing/files/292033/basic.mp4.txt)

**Comment by oysterboy** [comment]
Would it be possible to properly close the videoexport process 
whith a public method, 
ord does it need to be tied to Processing exiting,
I'm wondering..?

**Comment by hamoid** [comment]
I just realized that my videos were also all corrupted today. A few weeks ago I added some code to make sure dispose was called, but it seems it was breaking it, at least for me. I wonder if I should remove completely the dispose hook, and let users call dispose when they're done exporting the video... I'll test that and see how it works. Could you @oysterboy help me test in on Windows?

**Comment by hamoid** [comment]
I added a call to process.waitFor(); which seems to improve the situation very much. It does not go around the Processing bug (dispose() not being called), but it does make sure the end of the file is saved when dispose() is called. So if you call it manually, it should work now. 

I'll wait for your feedback before closing this issue.

**Comment by hamoid** [comment]
I added two methods that should get rid of this problem: startMovie() and endMovie(). Unfortunately this makes the code two lines longer, but I hope it gets rid of this issue.
