### ISSUE TITLE
the website is down? cannot download ZIP file from the site

### ISSUE THREAD

**Issue by ericwanderlust** [hamoid/video_export_processing#61]
Could you post an alternative link to down this library? [funprogramming.org](url) seems down...

Cannot even import this library from Processing. Really wanna try this. 

Thanks!!!!!

**Comment by hamoid** [comment]
Sorry about that. The hosting company messed up somehow. I released the files here at https://github.com/hamoid/video_export_processing/releases/tag/v23

**Comment by ericwanderlust** [comment]
> Sorry about that. The hosting company messed up somehow. I released the files here at https://github.com/hamoid/video_export_processing/releases/tag/v23

Thanks a lot! That helps me a lot!!
