### ISSUE TITLE
NullPointerException from startMovie() with very unhelpful error messages.

### ISSUE THREAD

**Issue by BricksAndPieces** [hamoid/video_export_processing#64]
I'm trying to use the VideoExport library but I keep running into a NullPointerException when startMovie() is called. Note that I am not using Processing but am using Java (with the processing jar).

```java
private VideoExport videoExport;

@Override
public void settings() {
    videoExport = new VideoExport(this, "video.mp4");
    videoExport.startMovie();
}
```

This is a simplified example of my code involving VideoExport. I am getting a Nullpointerexception that gives me no info on why it's caused or where exactly it's caused.

```
java.lang.NullPointerException
	at com.hamoid.VideoExport.startFfmpeg(Unknown Source)
	at com.hamoid.VideoExport.initialize(Unknown Source)
	at com.hamoid.VideoExport.startMovie(Unknown Source)
	at Test.settings(Test.java:108)
	at processing.core.PApplet.handleSettings(PApplet.java:978)
	at processing.core.PApplet.runSketch(PApplet.java:10897)
	at processing.core.PApplet.main(PApplet.java:10620)
	at Test.main(Test.java:244)
```

`Test.java:108` is the line startMovie() is called and `Test.java:244` is the main method. I was able to successfully set the path to ffmpeg so I don't think that is the issue. Might be wrong though.

If you have any idea what is going wrong, please let me know.

**Comment by hamoid** [comment]
Hi! What if you put the code inside setup `instead` of `settings`?

**Comment by BricksAndPieces** [comment]
This worked. I was under the impression that `settings` acted the same as `setup` in java because methods such as setting the size of the window only worked in `settings`. It worked perfectly now.
Thanks for the help!
