### ISSUE TITLE
NoSuchFieldError: frame on Processing4

### ISSUE THREAD

**Issue by hbarua05** [hamoid/video_export_processing#69]
I have previously used Video Export but upon installing the newer processing version I cant seem to render out my sketch as a video anymore. These are the errors shown.

![image](https://user-images.githubusercontent.com/66213858/132233565-9f87e72b-5a73-45c9-a18f-b1ed13aa666a.png)

**Comment by hamoid** [comment]
Thanks for reporting :) It seems I need to take a look into why this is happening...

**Comment by hamoid** [comment]
I'll take the opportunity to rewrite the library in Kotlin and build it using Gradle.

- [x] Make simple Gradle-based library written in Kotlin and test it in Processing 3 and 4.
- [ ] Port existing code to Kotlin
- [ ] Merge transparent-video feature

**Comment by hbarua05** [comment]
Thank you very much!

**Comment by hamoid** [comment]
Hi, I created a branch written in Kotlin and using Gradle to build. It can be found at 
https://github.com/hamoid/video_export_processing/tree/kotlinGradle

**Comment by hamoid** [comment]
Closing as the gradle branch seems to work in Processing 3 and 4.

**Comment by markuszeller** [comment]
Do I have to compile it by myself or can I use the released zip file?

**Comment by hamoid** [comment]
You don't need to compile it, just follow the instructions under "Using the library" on that link.

**Comment by markuszeller** [comment]
Great. That works on Processing 4.3 now. Thank you!
