### ISSUE TITLE
Videos running at half speed

### ISSUE THREAD

**Issue by scottmetoyer** [hamoid/video_export_processing#70]
My exports seem to be running at half speed. I've tested with the basic example; letting the sketch run for 5 seconds produces a 10 second file.

I'm using Processing 4 on a Mac (Monterey), using release 23 of the library. 

Any idea what I'm doing wrong?

**Comment by hamoid** [comment]
Hi! At what framerate is your sketch running? If it runs at 60 (the default) and the exported movie plays at 30 fps, it's normal that it looks like half speed.

**Comment by scottmetoyer** [comment]
Ah, that was it - so simple. Setting my framerate to 30 fixed the problem. Thanks!
