### ISSUE TITLE
Example of slow rendering avialable?

### ISSUE THREAD

**Issue by monbro** [hamoid/video_export_processing#9]
Hi, first of all thanks a lot for this lib! Its very helpful. You mentioning the following:

````
  // This sets the frame rate of the resulting video file. I has nothing to do
  // with the current Processing frame rate. For instance you could have a 
  // Processing sketch that does heavy computation and renders only one frame 
  // every 5 seconds, but here you could still set that the resulting video should 
  // play at 30 frames per second.  
  videoExport.setFrameRate(10);  
````

I hope I get this right. Do you have an example where my sketch renders e.g. a frame every second, so in 30 seconds I would have 30 frames generated which would be one second in the movie. Is this possible or correct? 

My goal was to change my sketch in a way, that I can achieve a higher framerate (30) for the video itself even if my processor and computing power is quite low for the heavy computing sketch.

**Comment by hamoid** [comment]
Hi! I don't have examples right now, but you don't need to do anything special to achieve this. If you have a slow calculation, it's enough to call videoExport.saveFrame(); when you're done with the calculation. The framerate in Processing would be slow, but that does not matter. When you play the video it would be played and the frame rate you specified with .setFrameRate()

A variation of this would be to not call .saveFrame() every time draw() is called, but only once in a while. For instance:

    if(frameCount % 90 == 89) {
        videoExport.saveFrame();
    }

This way it would save the frame once every 90 frames. This is useful only if you are not calling background() inside draw(), but adding more and more content to the screen.

Does that answer your question?
